# Exploratory Data Analysis

## 1. Introduction

This notebook performs exploratory data analysis (EDA) on the Early Stage Diabetes Risk Prediction dataset.

The objectives of this analysis are to:

- Understand the structure of the dataset.
- Examine the distribution of the target variable.
- Analyze numerical and categorical features.
- Identify potential data quality issues.
- Explore relationships between features and the target variable.
- Generate insights that will guide the preprocessing and machine learning stages.

In [67]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [68]:
df = pd.read_csv("../data/raw/diabetes_data_upload.csv")

In [69]:
df.head()

,Age,Gender,Polyuria,Polydipsia,sudden weight loss,weakness,Polyphagia,Genital thrush,visual blurring,Itching,Irritability,delayed healing,partial paresis,muscle stiffness,Alopecia,Obesity,class
0,40,Male,No,Yes,No,Yes,No,No,No,Yes,No,Yes,No,Yes,Yes,Yes,Positive
1,58,Male,No,No,No,Yes,No,No,Yes,No,No,No,Yes,No,Yes,No,Positive
2,41,Male,Yes,No,No,Yes,Yes,No,No,Yes,No,Yes,No,Yes,Yes,No,Positive
3,45,Male,No,No,Yes,Yes,Yes,Yes,No,Yes,No,Yes,No,No,No,No,Positive
4,60,Male,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Positive

In [70]:
df.shape

(520, 17)

In [71]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 520 entries, 0 to 519
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Age                 520 non-null    int64
 1   Gender              520 non-null    str
 2   Polyuria            520 non-null    str
 3   Polydipsia          520 non-null    str
 4   sudden weight loss  520 non-null    str
 5   weakness            520 non-null    str
 6   Polyphagia          520 non-null    str
 7   Genital thrush      520 non-null    str
 8   visual blurring     520 non-null    str
 9   Itching             520 non-null    str
 10  Irritability        520 non-null    str
 11  delayed healing     520 non-null    str
 12  partial paresis     520 non-null    str
 13  muscle stiffness    520 non-null    str
 14  Alopecia            520 non-null    str
 15  Obesity             520 non-null    str
 16  class               520 non-null    str
dtypes: int64(1), str(16)
memory usage: 69.2 KB

In [72]:
df.describe()

               Age
count   520.000000
mean     48.028846
std      12.151466
min      16.000000
25%      39.000000
50%      47.500000
75%      57.000000
max      90.000000

In [73]:
df["class"].value_counts()

class
Positive    320
Negative    200
Name: count, dtype: int64

In [74]:
# Note: The output above contained a matplotlib figure display object.